### ISSUE TITLE
filter() doesn't work 

### ISSUE THREAD

**Issue by piermariacosina** [kadamwhite/wordpress-rest-api#103]
running this 
```
wp.posts().filter( 'posts_per_page', 5 ).get(function( err, results ) {
	    if ( err ) {
	        // handle err
	    }
			// do something with the returned posts
				locals.data.posts = results;
				console.log(results);
				next();
			});
```
the result are always all the published post, with any kind of filter even 
```
wp.posts().filter({post_status: 'draft',category_name: 'news'}).get(function( err, results ) {
	    if ( err ) {
	        // handle err
	    }
			// do something with the returned posts
				locals.data.posts = results;
				console.log(results);
				next();
			})
```

Am I doing something wrong?

**Comment by kadamwhite** [comment]
Thanks for the report! I'll take a look. To help debug, what version of the wp-Api plugin are you using?

**Comment by piermariacosina** [comment]
Version 2.0-beta3 :)
ᐧ

On Mon, Jul 27, 2015 at 2:56 PM, K.Adam White <notifications@github.com>
wrote:

> Thanks for the report! I'll take a look. To help debug, what version of
> the wp-Api plugin are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kadamwhite/wordpress-rest-api/issues/103#issuecomment-125196660>
> .
>



-- 

PIERMARIA COSINA
User Experience Designer | Product Developer

+39 392 4822 633 <http://assets.belafonte.co/signature.html#>
www.belafonte.co
<http://www.belafonte.co/?utm_source=signature&utm_medium=email&utm_campaign=signature>

**Comment by piermariacosina** [comment]
Any news on this?

**Comment by kadamwhite** [comment]
@piermariacosina I have confirmed with the WP-API team that the URL should have changed to `?per_page=5`, from `filter[posts_per_page]=5`; I will make a change to enable this from the API library, but unfortunately I'm not seeing the "correct" new syntax work either on a 2.0 beta 4 API instance. If I get it working I'll update this and add a relevant method.

**Comment by kadamwhite** [comment]
@piermariacosina I am adding a `.perPage` method to handle this in the API v2 betas. It will be available in master shortly, and I will plan to tag it as a beta release on NPM.
