### ISSUE TITLE
Multiple categories?

### ISSUE THREAD

**Issue by chrisabrams** [kadamwhite/wordpress-rest-api#105]
Is there a way to fetch an article with multiple categories, such as article has category "foo" and "bar" ?

**Comment by kadamwhite** [comment]
@chrisabrams You should be able to pass `.category()` an array of category names:
```js
wp.posts().category(['foo', 'bar']).then(function(posts) { //...
```
If that doesn't work please let me know!

**Comment by chrisabrams** [comment]
If a post has three categories, then the above example doesn't seem to work.

**Comment by chrisabrams** [comment]
JK it does work. It would help if one of the categories wasn't `undefined`.

Notes:

This works as an AND for the selection, but as an OR for the whole set of categories on a post, meaning:

- Post A has categories ['foo', 'bar']
- Post B has categories ['foo', 'bar', 'baz],
- Post C has categories ['foo, baz']

It should only return posts A & B.

**Comment by kadamwhite** [comment]
Thanks for the notes; I've emerged from a busy summer of project work and will take this into account when revisiting the documentation and testing against the v2 API beta!
