### ISSUE TITLE
PUT (Update), POST (Create) examples?

### ISSUE THREAD

**Issue by eightyfive** [kadamwhite/wordpress-rest-api#112]
I didn't find any example on how to handle PUT & POST calls to the API?

That would be good to have a couple of examples in the wiki. As well as edge examples: inserting a new Post along with some new categories in one go.

**Comment by kadamwhite** [comment]
Thanks for the suggestion, you have an excellent point. Updating this library and refreshing the docs are one of my top priorities this month so I hope to have something to show in a few weeks!

**Comment by eightyfive** [comment]
Can you please share a quick example here?

This is preventing me to try out the library. I mean i can investigate myself, but if it's quick for you to share some code here, I would appreciate.

I'm looking for the way to inserts posts along with pre-defined categories attached to them.

Cheers.

**Comment by kadamwhite** [comment]
Which version of the API are you using? 1.x, or 2.x beta?

**Comment by eightyfive** [comment]
Dunno yet but I guess I want to use the latest. So let's say v2.

**Comment by eightyfive** [comment]
Hi,

So I tried with WP-API v2 but with no luck. So I decided to install WP-API v1.2.4 manually as well as [WP-API Basic Auth](https://github.com/WP-API/Basic-Auth) plugin.

But still no luck in creating a bunch of WP Users:

```js
var wp = new WP({
  endpoint: 'http://mysite.local:8080',
  username: 'eighty',
  password: 'passmethepassword',
});

wp
  .users()
  .post(users)
  .then(function(a1) {
    console.log(a1);
  })
  .catch(function(err) {
    console.log(err);
  })
  .finally(function() {
    process.exit(0);
  })
;
```

_Notes_:
- `err` is never reached
- `a1 = {}`
- No User is inserted in Database

**Comment by eightyfive** [comment]
Ok I could finally connect to my local JSON api (added `wp-json`):

```js
var wp = new WP({
  endpoint: 'http://mysite.local:8080/wp-json',
  username: 'eighty',
  password: 'passmethepassword',
});
```

(Commenting for documentation purpose)

**Comment by eightyfive** [comment]
It seems that I need a `nonce`:
https://github.com/WP-API/WP-API/issues/238

I have no idea what this is and how to include it in your library.

Any ideas?

https://codex.wordpress.org/WordPress_Nonces
http://wp-api.org/guides/authentication.html

**Comment by vtripolitakis** [comment]
This worked for me.

```javascript
var wp = new WP({
  endpoint: 'http://myendpoint',
  username: 'a_user',
  password: 'her_password',
});

wp.posts().post({
title:'a title',
excerpt:'the excerpt',
status:'draft',
content:'the content}).then(function (err,data)
{
	console.log(JSON.stringify(data));
	console.log(JSON.stringify(err));
});
```

**Comment by kadamwhite** [comment]
Apologies for the delayed response here. The README now contains instructions on [creating](https://github.com/kadamwhite/wordpress-rest-api#creating-posts) and [updating](https://github.com/kadamwhite/wordpress-rest-api#updating-posts) posts, in the "Using The Client" section. Here's the examples, both of which either require the use of a nonce (if you're requesting from the front-end) or the basic-auth plugin (if requesting from a Node server):

Create:
```js
// You must authenticate to be able to POST (create) a post
var wp = new WP({
    endpoint: 'http://your-site.com/wp-json',
    // This assumes you are using basic auth, as described further below
    username: 'someusername',
    password: 'password'
});
wp.posts().post({
    // "title" and "content" are the only required properties
    title: 'Your Post Title',
    content: 'Your post content',
    // Post will be created as a draft by default if a specific "status"
    // is not specified
    status: 'publish'
}).then(function( response ) {
    // "response" will hold all properties of your newly-created post,
    // including the unique `id` the post was assigned on creation
    console.log( response.id );
});
```
Update:
```js
// You must authenticate to be able to PUT (update) a post
var wp = new WP({
    endpoint: 'http://your-site.com/wp-json',
    // This assumes you are using basic auth, as described further below
    username: 'someusername',
    password: 'password'
});
// .id() must be used to specify the post we are updating
wp.posts().id( 2501 ).post({
    // Update the title
    title: 'A Better Title',
    // Set the post live (assuming it was "draft" before)
    status: 'publish'
}).then(function( response ) {
    console.log( response );
});
```
