### ISSUE TITLE
Upgrade route-parser to latest version

### ISSUE THREAD

**Issue by orditeck** [kadamwhite/wordpress-rest-api#119]
route-parser latest version is `0.0.4`, few issues have been fixed since `0.0.2`.

This one is maybe the most important and is currently annoying me: https://github.com/rcs/route-parser/issues/2

Would be nice if you could update that dependency.

**Comment by kadamwhite** [comment]
Great call; I'll audit the other deps too and get a new v2 compatibility beta out tomorrow (ditto v1 branch if you need it, otherwise I'll focus on the v2 branch)

**Comment by orditeck** [comment]
Great, thanks!

**Comment by kadamwhite** [comment]
@orditeck I've released v0.6.0-1, so `npm install wordpress-rest-api@beta` should get you the latest with the ^0.0.4 dependency. Thanks for the report!
