### ISSUE TITLE
Can't authenticate using basic authentication

### ISSUE THREAD

**Issue by andreipot** [kadamwhite/wordpress-rest-api#139]
hello @kadamwhite 
I'm using basic authentication via
var wp = new WP({
            endpoint: URL ,
            username: email,
            password: password,
            auth: true
        });
       wp.users().me().then(function(data){
           resolve(data);
       }, function(err){
           reject(err);
       });

However I get 403 error.
Any idea?

**Comment by andreipot** [comment]
I close this issue myself. I've resolved it.

**Comment by sebastienbarre** [comment]
How did you solve it, if I may ask?

**Comment by Ohar** [comment]
@andreipot I have the same question. Clarify your solutiion, plz.

**Comment by kadamwhite** [comment]
@ohar @sebastiennarre could you share sample code (without real password though ;) showing the requests you are making that are generating 403 errors?

**Comment by kadamwhite** [comment]
@ohar @sebastienbarre could you share sample code (without real password though ;) showing the requests you are making that are generating 403 errors?

**Comment by Ohar** [comment]
Oh I am sorry, it was problem on my side. 
I just didn`t install [WP API](https://github.com/WP-API/WP-API) plugin. 
It is not clear that *its a plugin, not a WordPress feature*. I was sure that REST API is a thing which WordPress has *out-of-the-box* and there no needs in any third-party plugins.

**Comment by kadamwhite** [comment]
@Ohar wish us luck today then, we're meeting with the WordPress leads tonight to decide whether these endpoints will be merged in to WordPresa core!
