### ISSUE TITLE
How can I retrieve a draft post?

### ISSUE THREAD

**Issue by yongzhihuang** [kadamwhite/wordpress-rest-api#154]
```    
const wp = new WP({
        endpoint: endpoint,
        username: username,
        password: password
});

wp.posts().filter({status: 'any'}).embed().id(id).then(function(data) {
    console.log(data)
})
```
When I try to retrieve an post that is set to draft, I'm unable to retrieve the post.  When I log the error, i got a 403 permission error.

```
error: 
      { [Error: cannot GET /wp-json/wp/v2/posts/631?_embed=true (403)]
        status: 403,
        text: '{"code":"rest_forbidden","message":"You don\'t have permission to do this.","data":{"status":403}}',
        method: 'GET',
        path: '/wp-json/wp/v2/posts/631?_embed=true' },
```

The user credential i sent to WP is a user with Admin privilege.

Thank you so much for your help!

**Comment by yongzhihuang** [comment]
Update, I was able to solve it by passing `auth: true` to the constructor object.  It works for a single draft post, but how can I make it work for a list of posts? Basically I would like to retrieve a list of posts that contains both published and drafts.

**Comment by yongzhihuang** [comment]
Figured it out. I have to chain 
```
.param({
        status: 'draft'
})
```

to the request!

**Comment by kadamwhite** [comment]
@yongzhihuang I'm sorry I haven't been responsive to this issue, I'm currently traveling—but yes, that's the solution! If you have time to make a PR I would love to get that added to the docs, it's definitely an omission; otherwise I'll leave this issue open to capture adding this later.

**Comment by yongzhihuang** [comment]
@kadamwhite I would love to! Will do when I have a chance.

Separate question: If I wanted to have the `status` field return to me when I'm querying a list of posts, how can I do that?

**Comment by kadamwhite** [comment]
@yongzhihuang "status" is a parameter that only appears when you are making a [posts collection query in the "edit" context](http://v2.wp-api.org/reference/posts/), as by default the API assumes that it is being used to display published data. To form a request that includes status, you can switch to the edit context via:

```js
// Chaining .auth seems to be necessary to activate authentication,
// even if the username/password were provided when creating
// the site handler instance
wp.posts().auth().param( 'context', 'edit' )...

// Get scheduled future posts:
wp.posts().auth().param( 'context', 'edit' ).param( 'status', 'future' )...

// Get draft posts:
wp.posts().auth().param( 'context', 'edit' ).param( 'status', 'draft' )...
```
Hope that helps, let me know if you have any further issues!

**Comment by kadamwhite** [comment]
@yongzhihuang I'm going to close this as provisionally solved, if you're still having trouble please re-open and let me know what issues you might be experiencing.

**Comment by michaelBenin** [comment]
If we know a post id and it's status is draft, is it possible to retrieve that with the node wp api?

**Comment by michaelBenin** [comment]
For example: 

```
wpApi
        .posts()
        .status([ 'draft', 'future' ])
        .id(id)
        .embed()
```
This gives a 403 everytime, in the constructor we are passing authentication.

**Comment by kadamwhite** [comment]
Is this using Cookie/Nonce authentication on the client, or Basic Authentication on the server? I assume you'd have checked this, but you are sure the user you're authenticating as can see the posts when they're logged in to the admin?

**Comment by motleydev** [comment]
Hi @kadamwhite, I am using this exact string `wp.posts().auth().param( 'context', 'edit' ).param( 'status', 'draft' )` to fetch drafts and I keep getting this error message:

    { code: 'rest_invalid_param',
      message: 'Invalid parameter(s): status',
      data: { status: 400, params: { status: 'Status is forbidden.' } } }

My auth works because I can create posts just fine, just fetching drafts is the issue.

**Comment by kadamwhite** [comment]
@michaelBenin I just realized that the request you describe
```js
wpApi
        .posts()
        .status([ 'draft', 'future' ])
        .id(id)
        .embed()
```
is invalid -- `.status` is not needed if you have the ID, `wpApi.posts().id( id ).embed()` should be sufficient. If you're getting a 403 then your auth works, but the user you're using to authenticate may not have proper permissions to view that post ID. This may not be related to your issue but I thought I'd leave the note here just in case.

**Comment by michaelBenin** [comment]
Hey - yea we got previews hooked up in our app. Thanks for reaching out again! And thanks for this awesome lib!
