### ISSUE TITLE
Updating pages/posts with large amount of copy throws error

### ISSUE THREAD

**Issue by nbyloff** [kadamwhite/wordpress-rest-api#155]
I am trying to save a large chunk of data to a post via API, but I am getting an error:

```javascript
Unhandled rejection Error: URI Too Long
superagent/lib/node.index.js:688:17
superagent/lib/node/index:js:911:12
```

I printed a few things to the console and noticed that all API requests are GET requests. Looking at the API documentation (and as a REST library), it should be using the POST & DELETE request types for creating, update and delete.

http://v2.wp-api.org/reference/pages/
http://v2.wp-api.org/reference/posts/

**Comment by kadamwhite** [comment]
@nbyloff Thanks for the report! Could you paste in the code chain you're using to create the request?

**Comment by nbyloff** [comment]
@kadamwhite sure thing. I am trying to post data to a custom field under pages/posts. The data is "critical CSS"; All CSS styles applied to above the fold content. This is the method where I am attempting this and causes the above error. Since it's a GET request, it fails. Please note, that while it's a custom field, anything default of a significant length (like body content), should fail too.

Thanks!

````javascript
function writeCssToDb(id, type, criticalCss) {

  if (type === 'post') {
    console.log('saving post: ' + id);

    wp.posts().id( id ).post({
        critical_css: criticalCss
    }).then(function( response ) {
      console.log('saved post to db');
      console.log(response);
      console.log(wp.posts().id( id ).get());
    });
  } else {

    console.log('saving page: ' + id);
    console.log('content: ' + criticalCss);
    wp.pages().id( id ).page({
        critical_css: criticalCss
    }).then(function( response ) {
        console.log(response);
        console.log('saved page to db');        
    });
  }
};
````

**Comment by kadamwhite** [comment]
That's unusual, I am trying `.post()`ing data to a local server and the requests are properly coming through as POSTs. Can you elaborate on your server setup, or how you're declaring the custom field?

**Comment by nbyloff** [comment]
No problem, but I don't think it will help since it's not complaining about saving, but the actual URL being submitted. I thought at first it might be because I am saving CSS, but that wouldn't shoot back an issue with the URL being too long. How long is the content you are submitting in your test? Does it have any HTML in it? 

I am going to try testing with the 'content' field, and submit over 1000 characters with some HTML in it to see what happens, then try it a much shorter submission with no HTML.I am pretty sure it's doing a GET request, so the vars are being placed in the URL. I'll try some different options like that today.

Anyways, as for setup, I am running a vagrant box. Vagrant setup is being built by [Trellis](https://roots.io/trellis/) package for building Wordpress. Here is how I am declaring my custom field. I am using Advanced Custom Fields (ACF) plugin for storing the data. The theme is their [Sage](https://github.com/roots/sage) theme. 


````javascript
function slug_get_post_meta_cb( $post, $field_name, $request ) 
{
	if (!is_object($post)) {
		return;
	}

  return get_field('critical_css', $post->id);
}
 
function slug_update_post_meta_cb( $value, $object, $field_name ) 
{
	error_log('updating inline css');
	if (!$value || !is_string($value)) {
		return;
	}
  update_field('critical_css', $value, $object->id);
    //return update_post_meta($post->ID, $field_name, $value);
}

add_action( 'rest_api_init', function() {
	register_api_field( 'page',
    	'critical_css',
    	array(
       		'get_callback'    => 'slug_get_post_meta_cb',
       		'update_callback' => 'slug_update_post_meta_cb',
       		'schema'          => null,
    	)
 	);
});

````

**Comment by nbyloff** [comment]
I used this website: http://www.blindtextgenerator.com/lorem-ipsum

Generated two blocks of text. One with 200 characters, one with 1000 characters.

200 characters: no errors
1000 characters: URI Too Long error.

It's not actually saving the text, but that's obviously a me error. Based on the API docs I linked in the OP, POST should be used for create & update, and a DELETE request for post/page removal. 

That way, large blocks of text like the main post content would be sent in the message body of a POST instead of being attached as a query var in the URL.

**Comment by kadamwhite** [comment]
Thanks, I understand the issue but I need to look into why it wouldn't be sending things by POST. I will investigate.

**Comment by nbyloff** [comment]
@kadamwhite ah gotcha, my bad. With my limited digging, I couldn't find where the module determined which request to use.

**Comment by nbyloff** [comment]
@kadamwhite Little more information. It looks like the issue is just with pages, not posts.

Posts seem to use a POST, but pages, uses GET. Noticed that I had content updating on posts and not pages, then noticed this in my error log.

(This is for a post, FYI)

````javascript
2016/03/21 14:36:29 [error] 7140#0: *63 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 127.0.0.1, server: localdev.dev, request: "POST /wp-json/wp/v2/posts/2627 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-wordpress.sock:", host: "localdev.dev"
````

Then this was in my access log (notice the difference between pages & posts).

````javascript
127.0.0.1 - nbyloff [21/Mar/2016:14:36:27 -0500] "GET /wp-json/wp/v2/pages/86?page%5Bcontent%5D=Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetuer%20adipiscing%20elit.%20Aenean%20commodo%20ligula%20eget%20dolor.%20Aenean%20massa.%20Cum%20sociis%20natoque%20penatibus%20et%20magnis%20dis%20parturient%20montes%2C%20nascetur%20ridiculus%20mus.%20Donec%20qu&page%5Bcritical_css%5D=Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetuer%20adipiscing%20elit.%20Aenean%20commodo%20ligula%20eget%20dolor.%20Aenean%20massa.%20Cum%20sociis%20natoque%20penatibus%20et%20magnis%20dis%20parturient%20montes%2C%20nascetur%20ridiculus%20mus.%20Donec%20qu HTTP/1.1" 200 475 "-" "node-superagent/1.8.2"
127.0.0.1 - nbyloff [21/Mar/2016:14:36:29 -0500] "POST /wp-json/wp/v2/posts/2627 HTTP/1.1" 200 872 "-" "node-superagent/1.8.2"
127.0.0.1 - nbyloff [21/Mar/2016:14:36:32 -0500] "GET /wp-json/wp/v2/pages/52?page%5Bcontent%5D=Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetuer%20adipiscing%20elit.%20Aenean%20commodo%20ligula%20eget%20dolor.%20Aenean%20massa.%20Cum%20sociis%20natoque%20penatibus%20et%20magnis%20dis%20parturient%20montes%2C%20nascetur%20ridiculus%20mus.%20Donec%20qu&page%5Bcritical_css%5D=Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetuer%20adipiscing%20elit.%20Aenean%20commodo%20ligula%20eget%20dolor.%20Aenean%20massa.%20Cum%20sociis%20natoque%20penatibus%20et%20magnis%20dis%20parturient%20montes%2C%20nascetur%20ridiculus%20mus.%20Donec%20qu HTTP/1.1" 200 976 "-" "node-superagent/1.8.2"
127.0.0.1 - nbyloff [21/Mar/2016:14:36:34 -0500] "POST /wp-json/wp/v2/posts/2593 HTTP/1.1" 200 879 "-" "node-superagent/1.8.2"
````

Side note/question: Is it possible to update with custom fields? I am only able to update content on a post. Page b/c of issue above. But my custom field isn't saving on a post, so wanted to double check that this is supported while I am digging.

**Comment by kadamwhite** [comment]
Ah, found it -- thanks for the detail, I'd overlooked the issue in the original code snippet. There's a linguistic issue involved in POSTing posts in a chaining API, in that in this library we use the http verbs as chain terminators and request initiators. When you say `wp.posts().id(6).post({})`, we are saying "POST an object to ID 6 within the posts collection." If we want to change it to be a requests against the pages collection, we swap the chain initiator, but not the request verb. So: `wp.pages().id(6).post({})`. In your snippet you have the code `wp.pages().id( id ).page({`... Page is a query parameter method that serialized and URL-encodes what you pass it. So what's happening is that the library is trying to convert your entire CSS into a pagination query parameter value, hence the long URL. Swap that to `.post({` and your irk problem should be resolved. 

As for submitting meta, it is possible; however, the way to handle meta has been in flux and I need to research the correct approach. I'll get back to you shortly.

**Comment by kadamwhite** [comment]
As an aside, we're considering aliasing or entirely moving to more English-language-semantic (and less HTML-y) request initiators, such as `wp.pages().create({})` or `wp.posts().id(7).update({})`. I'd be curious on your thoughts on this proposal as a user of the library.

**Comment by nbyloff** [comment]
Ugh. I totally see that now. I didn't read the docs completely. Glancing at the examples looked pretty straight forward for the small test I was doing. But yes, it works as expected now. It even seems to save my custom meta field data in my original example now. Going to see if it saves the actual CSS data tomorrow instead of my test data.

Personally, I'd like the library to mirror the actual commands, paths, requests, etc. you would see in the API, like you currently have in the library. It would make for a pretty simple one to one mapping for an API call to your method(s). Now that I know the last method on the chain is the actual request type and not referring to an internal WP post command, it's all clear & simple now.

I would tweak your readme file just a little bit for the skimmers like me to make it a little more clear. Make the comment on get, post, put, delete in the beginning of the examples and probably add a couple that aren't modifying posts. 

Again, sorry for the confusion. Had a launch over the weekend and I am getting diminishing returns last couple days. hah.
