### ISSUE TITLE
Get categories and tags for a specific post

### ISSUE THREAD

**Issue by justmarkup** [kadamwhite/wordpress-rest-api#156]
Is there a way to get all categories and tags for a post where I know the id.

I know there is wp-json/wp/v2/tags?post=[post_ID] and wp-json/wp/v2/categories?post=[post_ID]  - but how can I use this? 

I tried to use wp.taxonomies but couldn't find a way?

**Comment by kadamwhite** [comment]
The easiest way to get these two collections together in one request is to use the `_embed` parameter, accessible trough the .embed() method ― so, `wp.posts().id( x ).embed()`. That will pull down the post response with an extra ._embedded property, which will contain that post's tags, categories, author, and any other linked resource.

As for accessing these resource collections directly from their respective endpoints, somewhat counter-intuitively `/taxonomies` only gets you information about the resource itself: the response for `wp.taxonomies().taxonomy('category')`, for example, looks like this:
```json
{
	"name": "Categories",
	"slug": "category",
	"description": "",
	"types": ["post"],
	"hierarchical": true,
	"_links": {
		"collection": [{
			"href": "http:\/\/www.yoursite.com\/wp-json\/wp\/v2\/taxonomies"
		}],
		"https:\/\/api.w.org\/items": [{
			"href": "http:\/\/www.yoursite.com\/wp-json\/wp\/v2\/categories"
		}]
	}
}
```
The _links property specifies the collection endpoint, which is outside of the `/taxonomies` root. For this reason there are dedicated `wp.categories()` and `wp.tags()` collection query builder methods, each of which accepts a `forPost` chaining method:
```js
	wp.categories().forPost( post_ID ).then(function(cats) {
		console.log(cats);
	});

	wp.tags().forPost( post_ID ).then(function(tags) {
		console.log(tags);
	});
```
I hope this helps! Please re-open the issue if not, and we'll troubleshoot together. I'm tied up on another project right now but we'll hopefully be updating the documentation in conjunction with an upcoming re-write of the plugin to better leverage custom taxonomies and resources in the next month or so.

**Comment by justmarkup** [comment]
Thanks a lot @kadamwhite - didn't know about ```forPost()``` - exactly what I need.
