### ISSUE TITLE
Is there a way to retrieve all posts which are older or younger than ...

### ISSUE THREAD

**Issue by dasheck0** [kadamwhite/wordpress-rest-api#157]
Hi,

I was playing around with this library and now I have a special request. I want to fetch all wordpress posts, which are older than a value (represented as unix timestamp or formatted string).  The wordpress api has such a functionality (see https://github.com/WP-API/WP-API/issues/389#issuecomment-149210813).

I know there is a way to add some parameters to the base url in order to get them applied. But I doubt that this is the recommended way. Any help is appreciated.

Best regards
dasheck

**Comment by kadamwhite** [comment]
@dasheck0 You could do this with `.param( 'before', 'timestampstr' )`, but this is common enough functionality that I think we should add filter methods for it (so you can do `.before( 'timestampstr' )`, etc). Thanks for pointing out that had been added to the WP-API, I'd missed those PRs!

**Comment by kadamwhite** [comment]
Closed in favor of #179 which states the enhancement specifically
