### ISSUE TITLE
Integration Test Documentation

### ISSUE THREAD

**Issue by elyobo** [kadamwhite/wordpress-rest-api#159]
CONTRIBUTING.md recommends running `npm test`, but it appears that the integration tests have an external dependency on wpapi.loc (presumably some setup running locally?).  If there was some documentation available on how to run this it would allow us to verify that our changes don't break the integration tests either (and to add our own).

**Comment by kadamwhite** [comment]
Thanks for the catch, that's good feedback. I'm presenting on the library on Monday and hope to have some time to work on it over the weekend, so I'll see what I can throw together -- but the gist of it is, download and `vagrant up` with https://github.com/kadamwhite/wpapi-vagrant-varietal (misnomer as it is not formally a VVV derivative anymore) -- that'll pull down sample content and expose the URL that the tests expect to hit.

**Comment by elyobo** [comment]
OK, that's pretty straightforward, I followed the steps on the wpapi-vagrant-varietal repository and had no problems.

Perhaps just mentioning that users can run `npm test:unit` to run only the unit tests or, if they want to run the integration tests as well (which should be recommended) they'll need to set up the VM and to follow the steps there.

**Comment by kadamwhite** [comment]
@elyobo Good suggestion. If you're interested in sending a PR I'll merge it straight away, otherwise I'll leave this issue open to capture improving the docs.

**Comment by kadamwhite** [comment]
Closed by merging your PR, thank you!
