### ISSUE TITLE
Raw Content

### ISSUE THREAD

**Issue by jsteranko** [kadamwhite/wordpress-rest-api#166]
It there currently any way to retrieve raw content instead of rendered content?

**Comment by kadamwhite** [comment]
@jsteranko there is! If you authenticate and pass `.param('context', 'edit')`, you should see those raw values come back in the returned response.

**Comment by jsteranko** [comment]
Thanks @kadamwhite ! 

So it appears if I use that param, I lose the category filter, unless I'm doing something wrong. Example:

    function getAllPosts(req, res){
        wp.posts().auth().param('context', 'edit')
            .then(posts => {
                return res.status(200).json({success: true, posts: posts});
            })
            .catch(err => {
                return res.status(400).json({success: false, message: err.message});
            });
    }

and

    function getByCategory(req, res){
        var category = req.params.categoryName
        wp.posts(category).auth().param('context', 'edit') 
            .then(posts => {
                    return res.status(200).json({success: true, posts: posts});
               })
                 .catch(err =>{
                    return res.status(400).json({success: false, message: err.message});
              });
    } 

are returning the same content

**Comment by jsteranko** [comment]
@kadamwhite or anyone else - what am I doing wrong here (feel free to message me directly and close this)

**Comment by kadamwhite** [comment]
@jsteranko Unfortunately the options object you pass to `wp.posts()` doesn't have any ability to affect the query parameters of the response. To get a comment, you'd need to do this:
```js
wp.posts().auth().category( categoryName )...
```
Give that a try and let me know if it works out!

**Comment by jsteranko** [comment]
Works great. Thanks, and closing

**Comment by sebastienbarre** [comment]
Thank you, this helps. However, is it possible *not* to get the rendered content? This triggers any plugin that handles shortcodes and such, potentially making additional API queries for those that handle media like Flickr or Instagram.

**Comment by kadamwhite** [comment]
@sebastienbarre That is an interesting question; I am not sure there is a way to do that currently. I would encourage you to [open an issue on the Main WordPress REST API repository](https://github.com/WP-API/WP-API/issues/new), because the answer depends on the core plugin and not on this client.
