### ISSUE TITLE
Load Comments for posts not working. 

### ISSUE THREAD

**Issue by satish9323** [kadamwhite/wordpress-rest-api#169]
uncaughtException: wp.posts(...).id(...).comments is not a function

**Comment by aedensixty** [comment]
Can't remember why but I had to do something like this to get comments:

Obviously you can see I am also using a promise and handling errors for posts without comments, etc.

```
wp.posts().id(id).perPage(limit).page(page).embed().get(function(err, post) {
                Promise.resolve(null).then(function() {
                        if (!post || err) {
                            throw new Error('Post doesn\'t exist.');
                        }
                        if (!"_embedded" in post) {
                            throw new Error('Comments don\'t exist.');
                        }
                        var comments = post._embedded.replies;
                        if (!comments) {
                            throw new Error('Comments don\'t exist.');
                        }
                        resolve(comments);
                    })
                    .catch(function(err) {
                        resolve(err.message);
                    });
            });
```
Simplified

```
wp.posts().id(id).embed().get(function(err, post) {
     var comments = post._embedded.replies;
    console.log(comments);
 });
```

**Comment by kadamwhite** [comment]
@satish9323 Thanks for raising this, it's a major area of the API (i.e. this module's interface, not the "WP-API") that we're not satisfied with—the way that I converted the route builders from using the WP-APIv1 routes to use the new WP-APIv2 system "works," but broke the hierarchical relationship between comments and posts. To get comments, you now need to start from `wp.comments()` directly:
```js
wp.comments().forPost(id)...
```
That should return a paginated collection of comments for post `id`.

I'm going to close this as provisionally resolved, and open a new issue to investigate making `wp.posts().id( n ).comments()` function the same as `wp.comments().forPost( n )`—please re-open if this solution does not work for you.

**Comment by satish9323** [comment]
Thanks @kadamwhite . It worked.

**Comment by Barath-prakash** [comment]
@kadamwhite i cant create comment by using below code
wp.comments().post({
		    comment_post_ID: "postID",                               
		    user_id: "userID",                                              
		    comment_author: "authorName",                         
		    comment_author_email: "their-email@domain.com",
		    comment_content: "contentData"                            
		}).then(function( createdComment ) {
       console.log(createdComment);
       console.log( 'The comment was created with ID ' + createdComment.id );
   });

**Comment by Barath-prakash** [comment]
And i have trying with create too. but not working.
` wp.comments().create({
comment_post_ID: "postID",
user_id: "userID",
comment_author: "authorName",
comment_author_email: "their-email@domain.com",
comment_content: "contentData"
}).then(function( createdComment ) {
console.log(createdComment);
console.log( 'The comment was created with ID ' + createdComment.id );
});`

**Comment by Barath-prakash** [comment]
@kadamwhite i cant create comment by using below code

> wp.comments().post({
comment_post_ID: "postID",
user_id: "userID",
comment_author: "authorName",
comment_author_email: "their-email@domain.com",
comment_content: "contentData"
}).then(function( createdComment ) {
console.log(createdComment);
console.log( 'The comment was created with ID ' + createdComment.id );
});

**Comment by Barath-prakash** [comment]
@kadamwhite i cant post comment by using below code...
wp.comments().create({
comment_post_ID: "postID",
user_id: "userID",
comment_author: "authorName",
comment_author_email: "their-email@domain.com",
comment_content: "contentData"
}).then(function( createdComment ) {
console.log(createdComment);
console.log( 'The comment was created with ID ' + createdComment.id );
});
