### ISSUE TITLE
Post comment

### ISSUE THREAD

**Issue by satish9323** [kadamwhite/wordpress-rest-api#173]
I can not find anything related to post comments from wordpress-rest-api docs. Is it there and I am missing something ??? How can we post comments on posts ?? Please guide.

**Comment by kadamwhite** [comment]
You should be able to create a comment in the same basic way you [create a post](https://github.com/kadamwhite/wordpress-rest-api#creating-posts), using [these properties supported by the comment object](http://v2.wp-api.org/reference/comments/):
```js
var wp = new WP({ endpoint: 'http://my-site.com/wp-json/' });
wp.comments().post({
    post: 7,                                // The ID of the post to comment on
    author_email: 'their-email@domain.com', // The email of the author
    author_name: 'Author Display Name',     // Display name of the author
    content: 'This was a great article...'  // The textual content of the comment
}).then(function( createdComment ) {
    console.log( 'The comment was created with ID ' + createdComment.id );
});
```
Please re-open the issue if you run into trouble with that approach and we can help you troubleshoot—Thanks for using the library!

**Comment by photocurio** [comment]
Kadam, I'm using the above function to try to post comments. I get this 400 (bad request) error:
`https://topheavypilesofbooks.com/topheavy/wp-json/wp/v2/comments?post%5Bauthor_email%5D=oranges%40youtoo.com&post%5Bauthor_name%5D=gumble%20bumble&post%5Bcontent%5D=o%20give%20me%20a%20break%21%21&post%5Bpost%5D=1133`

If I put an error callback in the promise I get these tidbits:
`code : "rest_invalid_param"`
and 
`data : Object
    params : Object
        post : "post is not of type array."`
So what's that mean? Should the post be an array?

**Comment by kadamwhite** [comment]
Hello! I am terribly sorry for the confusion, @photocurio, a back-compat-breaking change got shipped since the above was posted: the `.post()` method has been renamed `.create()` to avoid confusion with the REST API's `post` query parameter.

Using the snippet
```js
var wp = new WP({ endpoint: 'http://my-site.com/wp-json/' });
wp.comments().create({
    post: 7,                                // The ID of the post to comment on
    author_email: 'their-email@domain.com', // The email of the author
    author_name: 'Author Display Name',     // Display name of the author
    content: 'This was a great article...'  // The textual content of the comment
}).then(function( createdComment ) {
    console.log( 'The comment was created with ID ' + createdComment.id );
});
```
should work! I never thought to audit old github threads for API changes when we shipped the new version.

**Comment by photocurio** [comment]
yup, that works.. and makes sense.

**Comment by Barath-prakash** [comment]
@kadamwhite this doesn't working for me.

var wp = new WP({ endpoint: 'http://my-site.com/wp-json/' });
wp.comments().create({
    post: 7,                                // The ID of the post to comment on
    author_email: 'their-email@domain.com', // The email of the author
    author_name: 'Author Display Name',     // Display name of the author
    content: 'This was a great article...'  // The textual content of the comment
}).then(function( createdComment ) {
    console.log( 'The comment was created with ID ' + createdComment.id );
});

**Comment by richarepo** [comment]
Hello there, I am getting this error --> "Sorry, you must be logged in to comment."
And also what is the key name for `parent_comment`?
