### ISSUE TITLE
Implement lo-dash/underscore support for return values

### ISSUE THREAD

**Issue by carldanley** [kadamwhite/wordpress-rest-api#5]
I had the idea of extending the return values to support lo-dash or underscore so the developer could make use of sorting functions (among everything else these libraries support).

Though, after talking with @kadamwhite - I feel that we should make this as lightweight as possible and let the developer choose how they want to take action on the return results.

Still opening the Issue for discussion on this topic.

**Comment by kadamwhite** [comment]
This has been deemed out-of-scope for the API as it is currently conceived; this would be a transformation the user would pass their data through when it is returned from the server, and is therefore something that they would be responsible for implementing to their needs. In pseudocode,

```js
wp.posts()
  .then( lodashify )
  .then(function( postCollection ) { /* ... */ });
```
