### ISSUE TITLE
Add convenience methods for filtering by dates

### ISSUE THREAD

**Issue by kadamwhite** [kadamwhite/wordpress-rest-api#61]
Possible options:

* .year()
* .month()
* .day()

Does WP support time-frame queries, like before/after?

**Comment by brad-decker** [comment]
@kadamwhite I'm working on this. Added the convenience methods to the PostsRequest class, and verified that they work. Haven't written any tests or anything.

**Comment by kadamwhite** [comment]
@brad-decker Awesome! Can you open a PR, so that it will be easier to track and respond to comments?
