### ISSUE TITLE
Make core lib environment agnostic to support use in the browser

### ISSUE THREAD

**Issue by matthewrobb** [kadamwhite/wordpress-rest-api#83]
It seems like a great deal of the value of this module would be useful in the browser as well, it wouldn't be too difficult to delegate all node specific code out into it's own location so that it can be swapped out for browser equivalents.

Is this something you all are potentially interested in? I could do this work.

**Comment by alexciarlillo** [comment]
I think this can be closed thanks to Browserify. It appears they shim most core libs that can be used from the browser now. I just just installed this via npm and required it into a React app built with Browserify no problem.

**Comment by kadamwhite** [comment]
That's great news -- do you have a demo or repo up I could check out? I'd like to see it in action before I close the issue, and I haven't had time to put a test together myself yet.

**Comment by alexciarlillo** [comment]
This is the repo I am working on: https://github.com/alexciarlillo/react-wp It is a WIP and is using ReactJS and RefluxJS for views and data-flow respectively. I can try to hammer out something simpler a little later if needed.

**Comment by kadamwhite** [comment]
This can be closed, browserify usage works OOTB.
